import { describe, expect, it } from "vitest";
import { AVATAR_IDS, DEFAULT_AVATAR_ID, isAvatarId } from "@/lib/domain/avatar";
import { Constants } from "@/types/database";
import { he } from "@/lib/i18n/he";

/**
 * The preset avatar set (Phase 4.3, docs/decisions/0019). What these lock down
 * is the ONE property the design depends on: `AVATAR_IDS`, the database enum
 * `public.avatar_choice`, and `he.avatars`' keys all name the exact same set,
 * so a thirteenth avatar cannot ship half-wired — present in one and silently
 * absent from another.
 */

describe("AVATAR_IDS matches the database enum exactly", () => {
  it("has the same members as public.avatar_choice, not merely the same count", () => {
    // `Constants.public.Enums.avatar_choice` is generated by
    // `npm run db:types` straight from the live enum (migration 0011) — this
    // is not a second hand-typed list to drift from the first, it is the
    // database's own answer, read at runtime.
    const fromDatabase = [...Constants.public.Enums.avatar_choice].sort();
    const fromDomain = [...AVATAR_IDS].sort();
    expect(fromDomain).toEqual(fromDatabase);
  });

  it("has no duplicate ids", () => {
    expect(new Set(AVATAR_IDS).size).toBe(AVATAR_IDS.length);
  });

  it("includes DEFAULT_AVATAR_ID as a real, selectable member", () => {
    expect(AVATAR_IDS).toContain(DEFAULT_AVATAR_ID);
  });
});

describe("every avatar has an accessible Hebrew name", () => {
  it("he.avatars has exactly one label per id, no more and no fewer", () => {
    // Same shape of check as tests/unit/role.test.ts and roleAndDemoLogin's own
    // parity assertions: a type-level guarantee (AvatarId as a Record key)
    // says nothing about a runtime dictionary someone edited by hand.
    expect(Object.keys(he.avatars).sort()).toEqual([...AVATAR_IDS].sort());
  });

  it("every label is real, non-empty text", () => {
    for (const id of AVATAR_IDS) {
      expect(he.avatars[id].trim().length, `label for ${id}`).toBeGreaterThan(0);
    }
  });
});

describe("isAvatarId — the guard a Server Action uses on client input", () => {
  it("accepts every real id", () => {
    for (const id of AVATAR_IDS) {
      expect(isAvatarId(id)).toBe(true);
    }
  });

  it("refuses anything that is not one of the twelve", () => {
    for (const bad of ["", "woman_short_haircut", "POMEGRANATE", "pomegranate ", "🍎"]) {
      expect(isAvatarId(bad), `input ${JSON.stringify(bad)}`).toBe(false);
    }
  });
});
